<a href="https://colab.research.google.com/github/lkmn-ai/knn-algorithm-notes/blob/main/04_KNN_Imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### KNN Imputer

In [ ]:
Univariate Technique >> Mean, Median, Mode of that particular feature only.

Multivariate Technique >> Use other rows to fill missing values

In [ ]:
Multivariate Technique:
    1. KNN Imputer
    2. Simple Imputer
    3. Mice (Multivariate Imputation by Chained Equation) Iterative Imputer

In [ ]:
It works on KNN algo basics
Simlarity Measure

Nan_Euclidean_distance = sqrt(wt * dist)
weights == no of cordinates (rowwise)/present no of cordinates
weights >> tries to compenset/balance ED for Missing cordinates

### Impuatation

In [ ]:
import pandas as pd
import numpy as np

from sklearn.impute import KNNImputer, SimpleImputer  # IterativeImputer

In [ ]:
dict1 = {'A':[13,19,17,np.nan, 11,14],
        'B':[40,45,48,50,41,44],
        'C':[2,6,1,8,9,5]}

df = pd.DataFrame(dict1)
df

      A   B  C
0  13.0  40  2
1  19.0  45  6
2  17.0  48  1
3   NaN  50  8
4  11.0  41  9
5  14.0  44  5

In [ ]:
df['A'].mean()

np.float64(14.8)

In [ ]:
knn_impute = KNNImputer(n_neighbors=5)
arr1 = knn_impute.fit_transform(df)
new_df = pd.DataFrame(arr1, columns=df.columns)
new_df

      A     B    C
0  13.0  40.0  2.0
1  19.0  45.0  6.0
2  17.0  48.0  1.0
3  14.8  50.0  8.0
4  11.0  41.0  9.0
5  14.0  44.0  5.0

In [ ]:
knn_impute = KNNImputer(n_neighbors=2)
arr1 = knn_impute.fit_transform(df)
new_df = pd.DataFrame(arr1, columns=df.columns)
new_df

      A     B    C
0  13.0  40.0  2.0
1  19.0  45.0  6.0
2  17.0  48.0  1.0
3  16.5  50.0  8.0
4  11.0  41.0  9.0
5  14.0  44.0  5.0

In [ ]:
(14+19)/2

16.5

In [ ]:
dict1 = {'A':[13,19,17,np.nan, 11,14],
        'B':[40,45,48,50,41,44],
        'C':[2,6,1,8,9,5]}

df = pd.DataFrame(dict1)
df

      A   B  C
0  13.0  40  2
1  19.0  45  6
2  17.0  48  1
3   NaN  50  8
4  11.0  41  9
5  14.0  44  5

In [ ]:
df['Dist'] = np.sqrt((50 - df['B'])**2 + (8 - df['C'])**2)
df

      A   B  C       Dist
0  13.0  40  2  11.661904
1  19.0  45  6   5.385165
2  17.0  48  1   7.280110
3   NaN  50  8   0.000000
4  11.0  41  9   9.055385
5  14.0  44  5   6.708204

In [ ]:
dict1 = {'A':[13,19,17,np.nan, 11,14],
        'B':[40,45,np.nan,50,41,44],
        'C':[2,6,1,8,9,5]}

df = pd.DataFrame(dict1)
df

      A     B  C
0  13.0  40.0  2
1  19.0  45.0  6
2  17.0   NaN  1
3   NaN  50.0  8
4  11.0  41.0  9
5  14.0  44.0  5

In [ ]:
df['Dist'] = np.sqrt((50 - df['B'])**2 + (8 - df['C'])**2)
df

      A     B  C       Dist
0  13.0  40.0  2  11.661904
1  19.0  45.0  6   5.385165
2  17.0   NaN  1        NaN
3   NaN  50.0  8   0.000000
4  11.0  41.0  9   9.055385
5  14.0  44.0  5   6.708204

In [ ]:
dict1 = {'A':[13,19,17,np.nan, 11,14],
        'B':[40,45,np.nan,50,41,44],
        'C':[2,6,1,8,9,5]}

df = pd.DataFrame(dict1)
df

      A     B  C
0  13.0  40.0  2
1  19.0  45.0  6
2  17.0   NaN  1
3   NaN  50.0  8
4  11.0  41.0  9
5  14.0  44.0  5

In [ ]:
knn_impute = KNNImputer(n_neighbors=4)
arr1 = knn_impute.fit_transform(df)
new_df = pd.DataFrame(arr1, columns=df.columns)
new_df

       A      B    C
0  13.00  40.00  2.0
1  19.00  45.00  6.0
2  17.00  44.75  1.0
3  15.25  50.00  8.0
4  11.00  41.00  9.0
5  14.00  44.00  5.0

### Categorical Data

In [ ]:
dict1 = {'A':[13,19,17,21, 11,14],
        'B':[40,45,16,50,41,44],
        'C':[2,6,1,8,9,5],
        'D':[1,0,0,1,np.nan,0]}

df = pd.DataFrame(dict1)
df

    A   B  C    D
0  13  40  2  1.0
1  19  45  6  0.0
2  17  16  1  0.0
3  21  50  8  1.0
4  11  41  9  NaN
5  14  44  5  0.0

In [ ]:
df.mean()

A    15.833333
B    39.333333
C     5.166667
D     0.400000
dtype: float64

In [ ]:
knn_impute = KNNImputer(n_neighbors=4)
arr1 = knn_impute.fit_transform(df)
new_df = pd.DataFrame(arr1, columns=df.columns)
new_df

      A     B    C    D
0  13.0  40.0  2.0  1.0
1  19.0  45.0  6.0  0.0
2  17.0  16.0  1.0  0.0
3  21.0  50.0  8.0  1.0
4  11.0  41.0  9.0  0.5
5  14.0  44.0  5.0  0.0

In [ ]:
knn_impute = KNNImputer(n_neighbors=1)
arr1 = knn_impute.fit_transform(df)
new_df = pd.DataFrame(arr1, columns=df.columns)
new_df

      A     B    C    D
0  13.0  40.0  2.0  1.0
1  19.0  45.0  6.0  0.0
2  17.0  16.0  1.0  0.0
3  21.0  50.0  8.0  1.0
4  11.0  41.0  9.0  0.0
5  14.0  44.0  5.0  0.0

### Outliers

##### Replace all outliers with Nan Values

In [ ]:
df = pd.read_csv('medical_insurance.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
df = df.select_dtypes(exclude=object).head(10)
df2 = df.copy()
df

   age     bmi  children      charges
0   19  27.900         0  16884.92400
1   18  33.770         1   1725.55230
2   28  33.000         3   4449.46200
3   33  22.705         0  21984.47061
4   32  28.880         0   3866.85520
5   31  25.740         0   3756.62160
6   46  33.440         1   8240.58960
7   37  27.740         3   7281.50560
8   37  29.830         2   6406.41070
9   60  25.840         0  28923.13692

In [ ]:
df['bmi'][2:5] = np.nan
df

C:\Users\cheta\AppData\Local\Temp\ipykernel_14312\1379785844.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['bmi'][2:5] = np.nan

   age    bmi  children      charges
0   19  27.90         0  16884.92400
1   18  33.77         1   1725.55230
2   28    NaN         3   4449.46200
3   33    NaN         0  21984.47061
4   32    NaN         0   3866.85520
5   31  25.74         0   3756.62160
6   46  33.44         1   8240.58960
7   37  27.74         3   7281.50560
8   37  29.83         2   6406.41070
9   60  25.84         0  28923.13692

In [ ]:
knn_impute = KNNImputer(n_neighbors=2)
arr1 = knn_impute.fit_transform(df)
new_df = pd.DataFrame(arr1, columns=df.columns)
new_df

    age     bmi  children      charges
0  19.0  27.900       0.0  16884.92400
1  18.0  33.770       1.0   1725.55230
2  28.0  33.000       3.0   4449.46200
3  33.0  22.705       0.0  21984.47061
4  32.0  28.880       0.0   3866.85520
5  31.0  25.740       0.0   3756.62160
6  46.0  33.440       1.0   8240.58960
7  37.0  27.740       3.0   7281.50560
8  37.0  29.830       2.0   6406.41070
9  60.0  25.840       0.0  28923.13692

### How do we get the Data

In [ ]:
Wrong Answers :
    Client
    CSV/EXCEL
    Given Ready Dataset through DB
    Data Engineer

In [ ]:
DB/DW : DataBase/DataWareHouse      >> Client

    Relational/Non-Relational:
        Cloud Based >> Amazon Redshift, DBFS, HDFS, S3 Bucket, ADLS Gen2
        Non-Cloud Based >> Oracle, Postgress, MongoDB, MySQL

    1. Client DB (SQL Server)
    prasad.pandey@hdfcbank.com (Some optional credentials could be there ex. IP Address, hostname, passwaord, ID, token)
    Virtual Server >> VDE (Virtual Desktop Environment) >> citrix, accorps, VMWare
    login >> servers
    Limitations >> no internet, no copying, One one Drive >> C-Drive
    Safe Environment

    >> df = pd.read_sql_query('select * from finance.accounts where acnt_type==Saving')

    2. Cloud based DB >> Amazon Redshift, DBFS, HDFS, S3 Bucket(AWS) >> Fetch >> Sagemaker >> Scripting
    3. DataBricks >> DBFS
    4. Data Engineers (DB) >> Query, Mail, a script
    5. Third Party APIs
    6. Web Scraping
    7. Kaggle, UCI Reporatories
    8. Non-Relational DBs, Drive(Very Less) (Folders with pdfs, images, text files)

In [ ]:
prasad.pandey@hdfcbank.com
prasadpandey@hdfcbank.com
prasadpandey1@hdfcbank.com
prasad.pandey1@hdfcbank.com

### Invalid Emails
prasadpandey007@hdfcbank.com
prasadpandey007@gmail.com
softheart07@gmail.com

In [ ]:
Great! Since you already know how **KNN** works (finding the nearest neighbors), **KNN Imputer** becomes very easy to understand.

---

# What is KNN Imputer?

**KNN Imputer** is a technique used to **fill missing values (NaN)** using the values of the **K nearest neighbors**.

Instead of filling missing values with the **mean**, **median**, or **mode**, it looks for **similar rows** and uses their values.

---

## Example

Suppose we have this dataset:

| Student | Age | Salary |
| ------- | --: | -----: |
| A       |  25 |  30000 |
| B       |  26 |  32000 |
| C       |  24 |      ❓ |
| D       |  27 |  34000 |
| E       |  50 |  80000 |

The salary of **Student C** is missing.

---

### Step 1: Choose K

Suppose:

```text
K = 2
```

---

### Step 2: Find the nearest neighbors

Since Student C has:

* Age = 24

The closest students are:

| Student | Age | Salary |
| ------- | --: | -----: |
| A       |  25 |  30000 |
| B       |  26 |  32000 |

Student E is much older (Age = 50), so they are **not** a close neighbor.

---

### Step 3: Fill the missing value

Take the average salary of the 2 nearest neighbors:

[
\frac{30000 + 32000}{2} = 31000
]

So the updated table becomes:

| Student | Age |      Salary |
| ------- | --: | ----------: |
| A       |  25 |       30000 |
| B       |  26 |       32000 |
| C       |  24 | **31000** ✅ |
| D       |  27 |       34000 |
| E       |  50 |       80000 |

---

# Why not use the mean?

Let's calculate the mean salary.

Available salaries:

```text
30000
32000
34000
80000
```

Mean:

[
\frac{30000+32000+34000+80000}{4}=44000
]

If we fill Student C's salary with **44,000**, does it make sense?

❌ No.

A 24-year-old earning **44,000** doesn't match similar students in the dataset.

KNN Imputer gives **31,000**, which is much more realistic because it uses **similar rows**.

---

# Visual Understanding

```text
Age

24  →  ?  (Need Salary)

25  → 30000   ← Nearest
26  → 32000   ← Nearest
27  → 34000
50  → 80000   (Far away)

Average of nearest neighbors

(30000 + 32000) / 2

= 31000
```

---

# Python Example

```python
from sklearn.impute import KNNImputer

import pandas as pd

df = pd.DataFrame({
    "Age": [25, 26, 24, 27, 50],
    "Salary": [30000, 32000, None, 34000, 80000]
})

imputer = KNNImputer(n_neighbors=2)

df_imputed = imputer.fit_transform(df)

print(df_imputed)
```

---

# Advantages

* ✅ Produces more realistic values than simply using the mean or median.
* ✅ Uses relationships between features.
* ✅ Works well when similar observations exist.

---

# Disadvantages

* ❌ Slow for large datasets because it computes distances.
* ❌ Requires feature scaling if features are on different scales.
* ❌ Less effective when many values are missing or the dataset is sparse.

---

# Interview Answer (30 seconds)

> **KNN Imputer** is a missing-value imputation technique that fills missing values by finding the **K nearest rows** based on the available features. For numerical data, it typically imputes the missing value using the **average** of the corresponding values from the nearest neighbors. It often produces more meaningful imputations than mean or median imputation because it considers the similarity between observations. Since it relies on distance calculations, **feature scaling is recommended before using KNN Imputer**.

In [ ]:
Let's understand your code **line by line**.

```python
from sklearn.impute import KNNImputer
```

This imports the **KNNImputer** class from scikit-learn.

---

### Line 1

```python
knn_impute = KNNImputer(n_neighbors=2)
```

Here, you create a **KNN Imputer object**.

* `n_neighbors=2` means:

  * For every missing value (`NaN`),
  * Find the **2 nearest rows**,
  * Use their values to fill the missing value.

Think of it as saying:

> "Whenever you see a missing value, look at the **2 most similar rows**."

---

### Line 2

```python
arr1 = knn_impute.fit_transform(df)
```

This is where the actual imputation happens.

It performs two steps:

### `fit()`

* Looks at your dataset.
* Learns where the missing values are.
* Calculates the distances between rows.

### `transform()`

* Replaces every missing value with the estimated value.

For example, if your original DataFrame is:

| Age | Salary |
| --: | -----: |
|  25 |  30000 |
|  26 |  32000 |
|  24 |    NaN |
|  27 |  34000 |

After `fit_transform()`:

| Age | Salary |
| --: | -----: |
|  25 |  30000 |
|  26 |  32000 |
|  24 |  31000 |
|  27 |  34000 |

---

### Why is the result stored in `arr1`?

`fit_transform()` returns a **NumPy array**, not a DataFrame.

Example:

```python
print(type(arr1))
```

Output:

```python
<class 'numpy.ndarray'>
```

The array looks like:

```python
[
 [25.0, 30000.0],
 [26.0, 32000.0],
 [24.0, 31000.0],
 [27.0, 34000.0]
]
```

Notice:

* There are **no column names**.
* There is **no DataFrame index**.

---

### Line 3

```python
new_df = pd.DataFrame(arr1, columns=df.columns)
```

This converts the NumPy array back into a **pandas DataFrame**.

* `arr1` → the imputed data.
* `columns=df.columns` → reuses the original column names.

So `new_df` becomes:

| Age | Salary |
| --: | -----: |
|  25 |  30000 |
|  26 |  32000 |
|  24 |  31000 |
|  27 |  34000 |

---

### Line 4

```python
new_df
```

This simply displays the new DataFrame.

---

## Overall Flow

```text
Original DataFrame
        │
        ▼
KNNImputer(n_neighbors=2)
        │
        ▼
Find 2 nearest rows
        │
        ▼
Replace NaN with estimated value
        │
        ▼
Returns NumPy Array
        │
        ▼
Convert Array → DataFrame
        │
        ▼
Final DataFrame
```

---

## Interview Question

**Q: Why do we convert the result back into a DataFrame?**

**Answer:**
`fit_transform()` returns a **NumPy array**, which doesn't preserve the original column names or index. Converting it back to a pandas DataFrame using `pd.DataFrame(..., columns=df.columns)` restores the original structure, making the data easier to read and work with.